<?php
/**
 * 存储驱动定义（后台表单动态渲染 + 帮助教程）
 * 每个驱动：label / icon / desc / fields / tips
 * field: name / label / type(text|password|number|select) / required / placeholder / default / help / options
 */

return [
    'local' => [
        'label'  => '本地存储',
        'icon'   => '💾',
        'desc'   => '图片保存在本机服务器磁盘',
        'fields' => [
            'path' => ['label' => '存储根目录', 'type' => 'text', 'required' => false,
                'placeholder' => '如 storage（默认用项目 storage 目录）',
                'help' => '绝对路径或相对项目根目录的路径，留空使用默认'],
            'url'  => ['label' => '公开访问 URL 前缀', 'type' => 'text', 'required' => false,
                'placeholder' => 'https://yourdomain.com',
                'help' => '图片对外访问的地址前缀，通常就是站点域名'],
        ],
        'tips' => '本地存储开箱即用，无需额外配置，适合单机部署。',
    ],

    'sftp' => [
        'label'  => 'SFTP 远程服务器',
        'icon'   => '🔐',
        'desc'   => '图片传到另一台服务器（走 SSH 加密）',
        'fields' => [
            'host' => ['label' => '服务器地址', 'type' => 'text', 'required' => true,
                'placeholder' => '如 123.45.67.89 或 sftp.example.com'],
            'port' => ['label' => '端口', 'type' => 'number', 'required' => true,
                'default' => '22', 'placeholder' => '22'],
            'username' => ['label' => '用户名', 'type' => 'text', 'required' => true,
                'placeholder' => 'SSH 登录用户名，如 www'],
            'password' => ['label' => '密码', 'type' => 'password', 'required' => false,
                'placeholder' => 'SSH 密码（用密钥认证可留空）',
                'help' => '与私钥二选一；服务器禁止密码登录时留空'],
            'private_key' => ['label' => '私钥文件路径', 'type' => 'text', 'required' => false,
                'placeholder' => '如 /home/www/.ssh/freeimg',
                'help' => '本机私钥绝对路径，同目录必须有 .pub 公钥文件'],
            'private_key_passphrase' => ['label' => '私钥密码（可选）', 'type' => 'password', 'required' => false,
                'placeholder' => '生成私钥时设置的密码，没有就留空'],
            'path' => ['label' => '远程存储目录', 'type' => 'text', 'required' => true,
                'placeholder' => '如 /home/www/uploads',
                'help' => '目标服务器上的绝对路径，需已存在且可写'],
            'public_url' => ['label' => '公开访问 URL 前缀（可选）', 'type' => 'text', 'required' => false,
                'placeholder' => 'https://img.example.com',
                'help' => '目标服务器能直接访问图片时的 URL；留空则图片仅存不展示'],
        ],
        'tips' => '适合把图片存到独立存储服务器/大硬盘机器。首次使用请看下方小白教程 👇',
        'tutorial' => 'sftp',
    ],

    's3' => [
        'label'  => 'S3 兼容存储',
        'icon'   => '☁️',
        'desc'   => 'AWS S3 / Cloudflare R2 / Backblaze / MinIO 等',
        'fields' => [
            'endpoint' => ['label' => 'Endpoint 地址', 'type' => 'text', 'required' => true,
                'placeholder' => '如 https://s3.us-east-1.amazonaws.com',
                'help' => 'R2: https://<accountid>.r2.cloudflarestorage.com'],
            'region' => ['label' => 'Region 区域', 'type' => 'text', 'required' => true,
                'default' => 'auto', 'placeholder' => '如 us-east-1 或 auto'],
            'bucket' => ['label' => 'Bucket 名称', 'type' => 'text', 'required' => true],
            'access_key' => ['label' => 'Access Key', 'type' => 'text', 'required' => true],
            'secret_key' => ['label' => 'Secret Key', 'type' => 'password', 'required' => true],
            'path_style' => ['label' => '地址风格', 'type' => 'select', 'required' => false,
                'default' => '1', 'options' => ['1' => 'Path 风格（bucket/文件）', '0' => '虚拟主机风格（bucket.域名）'],
                'help' => 'MinIO/自建 S3 用 Path 风格；AWS 云服务用虚拟主机风格'],
            'public_url' => ['label' => '公开访问 URL 前缀（可选）', 'type' => 'text', 'required' => false,
                'placeholder' => 'https://cdn.example.com',
                'help' => '一般留空自动生成；自定义 CDN 域名时填写'],
        ],
        'tips' => '一个配置通吃 AWS S3、Cloudflare R2、Backblaze B2、Wasabi、MinIO、华为云 OBS。',
    ],

    'cos' => [
        'label'  => '腾讯云 COS',
        'icon'   => '🐧',
        'desc'   => '腾讯云对象存储（COS XML API · TC3-HMAC-SHA256 签名）',
        'fields' => [
            'endpoint' => ['label' => 'Endpoint', 'type' => 'text', 'required' => true,
                'placeholder' => '如 cos.ap-guangzhou.myqcloud.com',
                'help' => 'COS 域名后缀，不要带 https:// 和桶名。例如 ap-guangzhou → cos.ap-guangzhou.myqcloud.com；ap-beijing-1 → cos.ap-beijing-1.myqcloud.com（注意 1 是真实的，不是笔误）'],
            'region' => ['label' => 'Region 区域', 'type' => 'text', 'required' => true,
                'placeholder' => '如 ap-guangzhou',
                'help' => '必须从 Endpoint 截取保持一致（ap-guangzhou / ap-beijing-1 / ap-shanghai 等），错一位就 403 SignatureDoesNotMatch'],
            'bucket' => ['label' => 'Bucket 名称', 'type' => 'text', 'required' => true,
                'placeholder' => '如 mybucket-1250000000',
                'help' => '完整桶名（含 -1250000000 后缀），从控制台"存储桶列表"直接复制'],
            'secret_id' => ['label' => 'SecretId', 'type' => 'text', 'required' => true,
                'placeholder' => '以 AKID 开头',
                'help' => '访问管理 → API 密钥管理 → SecretId'],
            'secret_key' => ['label' => 'SecretKey', 'type' => 'password', 'required' => true,
                'help' => '创建密钥时只显示一次，没保存就重新创建一个'],
            'scheme' => ['label' => '协议', 'type' => 'select', 'required' => false,
                'default' => 'https', 'options' => ['https' => 'HTTPS（推荐）', 'http' => 'HTTP'],
                'help' => '默认 HTTPS，国内环境用 HTTP 可能导致部分浏览器拦截'],
            'public_url' => ['label' => '公开访问 URL 前缀（可选）', 'type' => 'text', 'required' => false,
                'placeholder' => 'https://cdn.example.com',
                'help' => '绑定了 CDN 加速域名时填写，留空则自动拼桶域名'],
        ],
        'tips' => '⚠️ 桶需要在腾讯云控制台先建好，访问权限设为「公有读私有写」或「公有读写」才能公开访问图片。',
    ],

    'oss' => [
        'label'  => '阿里云 OSS',
        'icon'   => '☁️',
        'desc'   => '阿里云对象存储',
        'fields' => [
            'access_key_id' => ['label' => 'AccessKey ID', 'type' => 'text', 'required' => true],
            'access_key_secret' => ['label' => 'AccessKey Secret', 'type' => 'password', 'required' => true],
            'endpoint' => ['label' => 'Endpoint', 'type' => 'text', 'required' => true,
                'placeholder' => '如 oss-cn-hangzhou.aliyuncs.com'],
            'bucket' => ['label' => 'Bucket 名称', 'type' => 'text', 'required' => true],
            'public_url' => ['label' => '公开访问 URL 前缀（可选）', 'type' => 'text', 'required' => false],
        ],
        'tips' => '阿里云对象存储，按量付费，国内访问快。',
    ],

    'obs' => [
        'label'  => '华为云 OBS',
        'icon'   => '🌐',
        'desc'   => '华为云对象存储（OBS 原生签名 v2 · HMAC-SHA1）',
        'fields' => [
            'endpoint' => ['label' => 'Endpoint', 'type' => 'text', 'required' => true,
                'placeholder' => '如 obs.cn-north-4.myhuaweicloud.com',
                'help' => '从控制台 OBS → 桶列表 → 桶名 → 概览 → Endpoint 复制，不要带 https://'],
            'region' => ['label' => 'Region', 'type' => 'text', 'required' => true,
                'placeholder' => '如 cn-north-4',
                'help' => '从 Endpoint 截取前半段。obs.cn-north-4.myhuaweicloud.com → cn-north-4（上海一 cn-east-3、广州 cn-south-1、乌兰察布 cn-north-9 等）'],
            'bucket' => ['label' => 'Bucket 名称', 'type' => 'text', 'required' => true,
                'help' => 'OBS 控制台桶列表里的桶名。命名规则：小写字母、数字、短横线，3-63 字符'],
            'access_key' => ['label' => 'Access Key (AK)', 'type' => 'text', 'required' => true,
                'placeholder' => '以 HPUA 开头',
                'help' => '我的凭证 → 访问密钥 → Access Key ID。华为云 AK 通常以 HPUA 开头'],
            'secret_key' => ['label' => 'Secret Key (SK)', 'type' => 'password', 'required' => true,
                'help' => '创建访问密钥时只显示一次，丢失只能重新创建'],
            'public_url' => ['label' => '公开访问 URL 前缀（可选）', 'type' => 'text', 'required' => false,
                'placeholder' => 'https://cdn.example.com',
                'help' => '绑了 CDN/自有域名时填写。留空则用 https://{bucket}.{endpoint}/{文件路径}'],
        ],
        'tips' => '⚠️ 桶需在 OBS 控制台先建好，「桶策略」设为公共读（参考策略：Principal:* / Action: GetObject）才能公开访问图片。\n⚠️ 与 AWS S3 协议不兼容——OBS 使用华为云自有的 v2 签名（HMAC-SHA1），不是 AWS SigV4。',
    ],
];
